development:
  adapter: mysql2
  database: risd_development
  username: root
  host: localhost

test:
  adapter: mysql2
  database: risd_test
  username: root
  host: localhost

staging:
  adapter: mysql2
  database: risd_staging
  username: root
  host: localhost

production:
  adapter: mysql2
  database: oms_risd
  username: dp
  host: localhost
  password: 7yUaUhNFWfm3KsnPafi
